<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>VBScript Language Definition</string>
	<key>fileTypes</key>
	<array>
		<string>vbs</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?i)^\s*(Public|Private)?\s*(Class|Function|Sub|Property)\s*([a-zA-Z_]\w*)\s*(\(.*\)\s*)?$</string>
	<key>foldingStopMarker</key>
	<string>(?i)^\s*End (Class|Function|Sub|Property)\s*$</string>
	<key>name</key>
	<string>VBScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?i:^\s*(function|sub)\s*([a-zA-Z_]\w*)\s*(\()([^)]*)(\)))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.vbs</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.vbs</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.vbs</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.vbs</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.vbs</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.function.vbs</string>
			<key>end</key>
			<string>(?:^\s*end\s+\1)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.vbs</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:^\s*(class)\s*([a-zA-Z_]\w*))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.vbs</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.vbs</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.class.vbs</string>
			<key>end</key>
			<string>(?i:^\s*end\s+class)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.vbs</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.vbs</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(').*$\n?</string>
			<key>name</key>
			<string>comment.line.apostrophe.vbs</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.vbs</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(REM ).*$\n?</string>
			<key>name</key>
			<string>comment.line.rem.vbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(If|Then|Else|ElseIf|End If|While|Wend|For|To|Each|In|Step|Case|Select|End Select|Return|Continue|Do|Until|Loop|Next|With|Exit Do|Exit For|Exit Function|Exit Property|Exit Sub)\b)</string>
			<key>name</key>
			<string>keyword.control.vbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=|&gt;=|&lt;|&gt;|&lt;|&lt;&gt;|\+|-|\*|\^|&amp;|\b(?i:(Mod|And|Not|Or|Xor|Is))\b</string>
			<key>name</key>
			<string>keyword.operator.vbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Call|Class|Const|Dim|Redim|Function|Sub|Property|End Property|End sub|End Function|Set|Let|Get|New|Randomize|Option Explicit|On Error Resume Next|On Error GoTo)\b)</string>
			<key>name</key>
			<string>storage.type.vbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Private|Public|Default)\b)</string>
			<key>name</key>
			<string>storage.modifier.vbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Empty|False|Nothing|Null|True)\b)</string>
			<key>name</key>
			<string>constant.language.vbs</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.vbs</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"(?!")</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.vbs</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.vbs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>""</string>
					<key>name</key>
					<string>constant.character.escape.apostrophe.vbs</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.vbs</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\$)[a-zA-Z_x7f-xff][a-zA-Z0-9_x7f-xff]*?\b</string>
			<key>name</key>
			<string>variable.other.vbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(TotalBytes|Buffer|CacheControl|Charset|ContentType|Expires|ExpiresAbsolute|IsClientConnected|PICS|Status|ScriptTimeout|CodePage|LCID|SessionID|Timeout)\b)</string>
			<key>name</key>
			<string>support.constant.vbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:Class_(Initialize|Terminate))\b</string>
			<key>name</key>
			<string>support.function.event.vbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Lock|Unlock|SetAbort|SetComplete|BianryRead|AddHeader|AppendToLog|BinaryWrite|Clear|End|Flush|Redirect|Write|CreateObject|HTMLEncode|MapPath|URLEncode|Abandon)\b)</string>
			<key>name</key>
			<string>support.function.vbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Array|Add|Asc|Atn|CBool|CByte|CCur|CDate|CDbl|Chr|CInt|CLng|Conversions|Cos|CreateObject|CSng|CStr|Date|DateAdd|DateDiff|DatePart|DateSerial|DateValue|Day|Derived|Math|Escape|Eval|Exists|Exp|Filter|FormatCurrency|FormatDateTime|FormatNumber|FormatPercent|GetLocale|GetObject|GetRef|Hex|Hour|InputBox|InStr|InStrRev|Int|Fix|IsArray|IsDate|IsEmpty|IsNull|IsNumeric|IsObject|Item|Items|Join|Keys|LBound|LCase|Left|Len|LoadPicture|Log|LTrim|RTrim|Trim|Maths|Mid|Minute|Month|MonthName|MsgBox|Now|Oct|Remove|RemoveAll|Replace|RGB|Right|Rnd|Round|ScriptEngine|ScriptEngineBuildVersion|ScriptEngineMajorVersion|ScriptEngineMinorVersion|Second|SetLocale|Sgn|Sin|Space|Split|Sqr|StrComp|String|StrReverse|Tan|Time|Timer|TimeSerial|TimeValue|TypeName|UBound|UCase|Unescape|VarType|Weekday|WeekdayName|Year)\b)</string>
			<key>name</key>
			<string>support.function.vbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f)?\b</string>
			<key>name</key>
			<string>constant.numeric.vbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(vb(true|false|cr|crlf|formfeed|lf|newline|nullchar|nullstring|tab|verticaltab|binarycompare|textcompare|sunday|monday|tuesday|wednesday|thursday|friday|saturday|usesystemdayofweek|firstjan1|firstfourdays|firstfullweek|generaldate|longdate|shortdate|longtime|shorttime|objecterror|Empty|Null|Integer|Long|Single|Double|Currency|Date|String|Object|Error|Boolean|Variant|DataObject|Decimal|Byte|Array))\b)</string>
			<key>name</key>
			<string>support.type.vbs</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.vbs</string>
	<key>uuid</key>
	<string>60377C4C-7E92-4D78-9F28-D657BEB422C0</string>
</dict>
</plist>
